### ISSUE TITLE
regex - xxx and password

### ISSUE THREAD

**Issue by thezoggy** [kevinlekiller/Newznab-Blacklist#8]
tv shows sometimes have xxx or password in its show name/ep name. so these regex need to be mindful of that...

some examples of valid things it may catch that shouldn't:

```
Million.Dollar.Password.S02E01.PDTV.XVID-BAJSKORV
Robot.Chicken.S02E10.Password.Swordfish.DVDRip.XviD-SAiNTS
Bellator Fighting Championships S03E11 XXXIII HDTV XviD-QCF
```

one password format we should catch is `[Password]`,

found for example in:

```
Guilty Hearts [Bluray - Untouched] [usenet-4all.info] [Password] [powered by ssl-news.info] [18,74 GB] [139/207] "usenet-4all_4044.part137.rar" yEnc
The Four [Bluray - Untouched] [usenet-4all.info] [Password] [powered by ssl-news.info] [23,77 GB] [014/260] "usenet-4all_4043.part012.rar" yEnc
```

the usnet4all have a whitelist.. so not sure if catching it would be an issue though

**Comment by thezoggy** [comment]
found another 'dubbed' format to add: `DubbeD`
`Aladdin and King Of Thieves XViD DVDRiP Heb DubbeD-DDL-IL`

**Comment by thezoggy** [comment]
and just to check on password/xxx as tvshows..

!tvdb PASSWORD
< Show: Password (Game Show) :: Premiered: 1961-10-01 :: Airtime: -N/A- (-N/A-) :: Status: Ended :: URL: http://thetvdb.com/?tab=series&id=70823 :: TV.COM: http://www.tv.com/show/1133/summary.html >

!tvdb xxx
< Show: Mommy XXX (Reality) :: Premiered: 2009-06-18 :: Airtime: -N/A- (-N/A-) :: Status: Ended :: URL: http://thetvdb.com/?tab=series&id=262249 :: TV.COM: -N/A- >

**Comment by kevinlekiller** [comment]
I'll have to read more on regex to see how to exclude if it has the word TV in it.
